### PR TITLE
Update category-children.blade.php

### PR DESCRIPTION
**Pull request by bhaskarGit12345**
# Multi level category

### CODE REVIEW

**Comment by jsdecena** [comment]
@bhaskarGit12345 You cannot just do that. It will have `n+1` issue and will have infinite loop. That is why I propose to use [nested set](https://github.com/Laracommerce/laracom/issues/60)

**Comment by bhaskarGit12345** [comment]
In first test it was failed. Then i disabled **xdebug.max_nesting_level**.. Then the test was passed.

**Comment by belguinan** [comment]
> @bhaskarGit12345 You cannot just do that. It will have `n+1` issue and will have infinite loop. That is why I propose to use [nested set](https://github.com/Laracommerce/laracom/issues/60)

I updated categories to use nested set, It works really great but you have to remove eloquence search trait

**Comment by jsdecena** [comment]
@belguinan I think that would be great! We can remove the search trait since we are not searching for categories but products in those categories. :) It would be very helpful

**Comment by bhaskarGit12345** [comment]
> > @bhaskarGit12345 You cannot just do that. It will have `n+1` issue and will have infinite loop. That is why I propose to use [nested set](https://github.com/Laracommerce/laracom/issues/60)
> 
> I updated categories to use nested set, It works really great but you have to remove eloquence search trait

where can i find it ?

**Comment by belguinan** [comment]
> @bhaskarGit12345 He might not have pushed yet.

I will make a PR for it,

**Comment by jsdecena** [comment]
@bhaskarGit12345 There is already a PR for nested set categories

**Pull request closed without merging**
