### PR TITLE
Fix validation

### PR DESCRIPTION
**Pull request by marpal71**
# Erroneous handling of user input at Cart forms

## On the http://localhost/{product} and the http://localhost/cart , the 'Quantity' field accept not integer inputs. By applying 'add' button or 'update' button respectively, an application error reise if non integer is inserted.

  Just extended validation to handle non integer values.

Regards.

### CODE REVIEW

**Comment by jsdecena** [comment]
@marpal71 Thanks for this but can you remove the `composer.lock` file from the PR? I don't think there is a need to do composer update on this PR. Cheers! 🎉

**Comment by marpal71** [comment]
HI Jeff, i did making a new commit.

  If you prefer I can amend my last commit.

Let me know

Il giorno mer 27 mar 2019 alle ore 17:11 Jeff Simons Decena <
notifications@github.com> ha scritto:

**Comment by jsdmultisys** [comment]
@marpal71 The composer lock is still checked in

**Comment by marpal71** [comment]
I Will try amending my commit. MY be I will be necessary cancel my pull
request and making new one after amending. I'll let you know as soon I can
do it..
Cheers

Il ven 29 mar 2019, 08:00 Jeff Simons Decena <notifications@github.com> ha
scritto:

**Comment by marpal71** [comment]
Closing to request e new pull request without the unwanted composer.lock file.

**Comment by marpal71** [comment]
Hi Jeff, I closed #166 and opened #167. Is this one (#167) as you like ?.
   Cheers


Il ven 29 mar 2019, 08:06 Marco Palmerio <mapalmerio@gmail.com> ha scritto:

**Pull request closed without merging**
