### PR TITLE
- Integrated spatie/phpunit-watcher

### PR DESCRIPTION
**Pull request by sebbaum**
# Integration of [spatie/phpunit-watcher](https://github.com/spatie/phpunit-watcher)

## Description of the PR with the link on the issue trying to solve
My PR solves issue #116 by integrating spatie/phpunit-watcher. This laravel packages is a huge benefit in the context of unit/integration testing.
Every code change will automatically trigger a test run.
You get instant feedback if your tests are broken.

In order to use phpunit-watcher, follow these steps:
```
composer install
vendor/bin/phpunit-watcher watch
```

You'll find the basic configuration in `.phpunit-watcher.yml`
For more information about the package and configuration possibilities have a look at the offical documentation.
https://github.com/spatie/phpunit-watcher

In order to show desktop notifications on a Linux system, you have to install `libnotify-bin`
```
sudo apt install libnotify-bin
```

Cheers
Sebastian

### CODE REVIEW

**Comment by sebbaum** [comment]
@phannaly Well if you work test driven always running the tests manually feels also annoying. ;-)

>It makes you as a developer responsible to your own code.
That's true but for testing in general. phpunit-watcher only facilitates running the tests. 

You might not have noticed: You can also run only the test in a certain scope. You do not have to run always all tests.

Cheers
Sebastian

**Comment by jsdecena** [comment]
We can leave it to the devs if they want it to have this feature. I had something like this before but I do that in pre commit hook. So before they commit, the phpunit runs and most of the time, my devs don't really like it. If more people would request this feature, we can get this into the master branch. :)

**Comment by sebbaum** [comment]
@jsdecena Fair enough. :ok_hand:

**Comment by belguinan** [comment]
@jsdecena It would be great if we have it

**Comment by jsdecena** [comment]
You can have this in your forks. Thanks!

**Pull request closed without merging**
