### PR TITLE
Feature: Create Laracom base structure with a single command

### PR DESCRIPTION
**Pull request by belguinan**
### artisan make:strucutre

This command can help maintaining the same Laracom default structure while the project gets larger/complex.
@jsdecena uses a base repository and interface to test and create any model. Nested structure for each folder under `Shop/` help to organize the project better.

I think it's good to have this kind of commands so we can maintain the same architecture.
If you find it useful we can improve it.

#### How it works ?

`php artisan make:structure product`

This will create under `Shop` 

`/Shop/Products/Product.php`
`/Shop/Products/Repositories/ProductRepository.php`
`/Shop/Products/Repositories/Interfaces/ProductRepositoryInterface.php`
`/Shop/Products/Requests`

### CODE REVIEW

**Comment by jsdecena** [comment]
@belguinan Why not we do it like WordPress where the category id 1 is called `uncategorized`? then all children of this will be the top level category? Also, this will be seen beforehand if we have test first.

**Comment by jsdecena** [comment]
@belguinan Oh this PR is for a different issue right? Can we have it in a separate PR so we can refer to it later?

**Comment by belguinan** [comment]
> @belguinan Why not we do it like WordPress where the category id 1 is called `uncategorized`? then all children of this will be the top level category? Also, this will be seen beforehand if we have test first.

It's not good to have one single root category, for performance reason.
It's better if we make it optional to assign a category with a parent. so when user needs only root categories it's really fast to select them.

**Comment by belguinan** [comment]
> @belguinan Oh this PR is for a different issue right? Can we have it in a separate PR so we can refer to it later?

@jsdecena Okey i'll do it.

**Pull request closed without merging**
